---

settings:
  import/resolver:
    node:
      extensions:
      - '.js'
      - '.jsx'
      - '.ts'
      - '.tsx'

env:
  node: true
  browser: true
  jest: true

parser: babel-eslint

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'airbnb-base'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - jest
  - babel
rules:
  no-console: 0
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0